---
- name: Install Bamboo on docker containers
  hosts: webservers
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/lo

    - name: Create Bamboo directory
      file:
        path: /opt/bamboo
        state: directory

    - name: Copy Docker Compose file
      copy:
        src: /home/ansadmin/bamboo-docker/docker-compose.yml
    - name: Replace Docker compose file


          tjowithoeiwio
